name: Ubuntu
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  SCHEME: scheme
  IDRIS2_TESTS_CG: chez
  IDRIS2_COMMIT: "0bc18bd34a53824cafa5a72d7790ca380648636a"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
          sudo apt-get install -y chezscheme
          echo "$HOME/.idris2/bin" >> $GITHUB_PATH
      - name: Install Idris 2
        run: |
          git clone https://github.com/idris-lang/Idris2
          cd Idris2
          git reset --hard ${{ env.IDRIS2_COMMIT }}
          make bootstrap && make install
          cd ..
      - name: Build and test Idris2-Effect
        run: make build && make test INTERACTIVE=''
        shell: bash
